markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: wenxiyong
author: "zero"
email: 121018413@qq.com
name: "0 to Zero"
url: #http://www.panxw.co
domain: #www.panxw.com
all_categories: [
["read", "读书笔记","/posts/read.html"],
["javaDesign", "java方案设计","/posts/javaDesign.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
